### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#6]
Can we icorporate the shadow? Looks ace when the shirt is floating

**Comment by organised** [comment]
Yeah would like to, but tricky to fit it in a way that works.  originally was going to have it on the page separate from the construct canvas, as an image element underneath, but now that the page scales. (might have to disable this) I've got to make the shadow scale too underneath it.

**Comment by organised** [comment]
<img width="1083" alt="screen shot 2018-06-16 at 21 38 29" src="https://user-images.githubusercontent.com/3727889/41502243-d687a80e-71ad-11e8-885d-daae0f3068d3.png">

managed to squeeze it in, compared to the original designs seen below, its a little bit tighter, but IMO it's better than it not being there altogether. I'm gonna close this issue. because this was an easy fix and not as much priority as say fixing mobile. if we need it tweaking then we'll have to revisit it for version 2. 

<img width="668" alt="screen shot 2018-06-16 at 21 40 41" src="https://user-images.githubusercontent.com/3727889/41502249-18a4c028-71ae-11e8-8543-8660dd9e5209.png">
